project_id = "hkzgxdmnvyoviwketxva"

[db]
major_version = 15

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.send-daily-report]
verify_jwt = false

[functions.send-subscription-notification]
verify_jwt = false