// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_KEY;

// Custom fetch to gracefully handle fetch requests and 401 fallbacks without corrupting auth tokens
const customFetch: typeof fetch = async (url, options) => {
  try {
    const response = await fetch(url, options);

    if (response.status === 401 && options?.headers) {
      const urlStr = typeof url === 'string' ? url : (url as any)?.url || '';
      const isAuthEndpoint = urlStr.includes('/auth/v1/');

      if (!isAuthEndpoint) {
        const headers = new Headers(options.headers);
        const authHeader = headers.get('Authorization');
        const anonBearer = `Bearer ${SUPABASE_PUBLISHABLE_KEY}`;

        if (authHeader && authHeader !== anonBearer) {
          headers.set('Authorization', anonBearer);
          try {
            return await fetch(url, { ...options, headers });
          } catch {
            return response;
          }
        }
      }
    }

    return response;
  } catch (err: any) {
    throw err;
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    fetch: customFetch,
  },
  db: {
    schema: 'public'
  }
});